services:
  bot:
    build:
      dockerfile: ./Dockerfile_Bot
    image: bot_hades:latest
    networks:
      back:
        ipv4_address: 172.15.235.5
      default:
    volumes:
      - ./:/bot:./
    depends_on:
      mysql_db:
        condition: service_healthy
        restart: true
      rabbitmq_container:
        condition: service_started
    restart: unless-stopped


  hades:
    build:
      dockerfile: ./Dockerfile_Hades
    image: hades:latest
    ports:
      - 455:455
    volumes:
      - ./:/bot:./
    networks:
      back:
        ipv4_address: 172.15.235.6

    depends_on:
      mysql_db:
        condition: service_healthy
        restart: true
      rabbitmq_container:
        condition: service_started
      bot:
        condition: service_started
    restart: unless-stopped



  mysql_db:
    image: mysql:latest
    networks:
      back:
        ipv4_address: 172.15.235.2
    environment:
      MYSQL_ROOT_PASSWORD: root1234567890
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      start_period: 30s
      interval: 10s
      timeout: 20s
      retries: 5
    restart: unless-stopped


  rabbitmq_container:
    image: rabbitmq:latest
    networks:
      back:
        ipv4_address: 172.15.235.7
    restart: unless-stopped



networks:
  back:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.15.235.0/24
  default:
    driver: bridge